git:
  autoForwardBranches: "none"
keybinding:
  universal:
    prevItem-alt: 'l' # go one line up
    nextItem-alt: 'k' # go one line down
    prevBlock-alt: 'j' # goto the previous block / panel
    nextBlock-alt: ';' # goto the next block / panel

