#!/bin/sh

BAR_ICON=""

if ! updates=$(checkupdates 2> /dev/null | wc -l ); then
    updates=0
fi

if [ "$updates" -gt 0 ]; then
  echo "%{F#a3be8c}$BAR_ICON%{F-} $updates Updates"
else
  echo "%{F#a3be8c}$BAR_ICON%{F-} Up to date"
fi
