#!/bin/sh

session="dev"

tmux new-session -d -s $session

window=1

tmux rename-window -t $session:$window editor
tmux send-keys -t $session:$window '$EDITOR .' C-m

window=2

tmux new-window -t $session:$window -n shell

# window=3
#
# tmux new-window -t $session:$window -n git
# tmux send-keys -t $session:$window 'lazygit' C-m

window=1

tmux select-window -t $session:$window

tmux attach-session -t $session
