#!/bin/sh

cat > .prettierrc.mjs<< EOL
/**
 * @see https://prettier.io/docs/configuration
 * @type {import("prettier").Config}
 */
const config = {
  editorconfig: true,
  semi: false,
  singleQuote: true,
};

export default config;

EOL
