#!/bin/sh

cat > .prettierrc<< EOL
{
  "editorconfig": true,
  "semi": false,
  "singleQuote": true,

  "importOrderTypeScriptVersion": "5.8.3",
  "importOrder": [
    "<BUILTIN_MODULES>",
    "^(react/(.*)$)|^(react$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/styles/(.*)$",
    "",
    "^@/config/(.*)$",
    "^@/pages/(.*)$",
    "^@/components/(.*)$",
    "^@/hooks/(.*)$",
    "^@/services/(.*)$",
    "^@/models/(.*)$",
    "^@/constants/(.*)$",
    "^@/utils/(.*)$",
    "",
    "^[./]"
  ],

  "tailwindStylesheet": "./src/styles/index.css",
  "tailwindPreserveWhitespace": true,
  "tailwindFunctions": ["cva", "tw"],

  "plugins": [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss"
  ]
}

EOL

cat > .prettierignore<< EOL
node_modules
package-lock.json
pnpm-lock.yaml
public

EOL
