#!/bin/bash

# import colors from pywal
. "${HOME}/.cache/wal/colors.sh"

option=$(echo -e "Logout\nSuspend\nHibernate\nReboot\nShutdown" | rofi -dmenu -i -p "Off options" -lines 5);

case "$option" in
  "Logout") i3-msg exit;;
  "Suspend") betterlockscreen -s blur;;
  "Hibernate") systemctl hibernate;;
  "Reboot") systemctl reboot;;
  "Shutdown") systemctl poweroff;;
esac
