#!/bin/bash

# import colors from pywal
. "${HOME}/.cache/wal/colors.sh"

# option=$(echo -e "Logout\nSuspend\nHibernate\nReboot\nShutdown" | dmenu -i -p "Off options" -fn "Ubuntu Mono:pixelsize=19" -nb "$color0" -nf "$color8" -sb "$color4" -sf "$color0");
option=$(echo -e "Logout\nSuspend\nHibernate\nReboot\nShutdown" | rofi -dmenu -i -p "Off options");

case "$option" in
  "Logout") i3-msg exit;;
  "Suspend") betterlockscreen -s blur;;
  "Hibernate") systemctl hibernate;;
  "Reboot") systemctl reboot;;
  "Shutdown") systemctl poweroff;;
esac
