#!/bin/bash

layout="$(setxkbmap -query | grep layout | awk '{print $2}')"

if [ $layout = "us" ]; then
  setxkbmap workman;
  xset r 66;
  pidof dunst && notify-send "Keyboard: workman";
else
  setxkbmap us;
  xset -r 66;
  pidof dunst && notify-send "Keyboard: en-us";
fi

