#!/bin/sh

usage() {
  echo "Usage: $0 [-r <command>] [-h]" 2>&1
  echo '  -r COMMAND    Runs command on the top left pane'
  echo '  -h            Shows this text'
  exit 1
}

run() {
  command=$1
  session="dev"

  tmux new-session -d -s $session

  window=1

  tmux split-window -v
  tmux send-keys 'lazygit' C-m

  tmux select-pane -U
  tmux split-window -h
  tmux send-keys 'code .' C-m

  if [[ ${command} ]]; then
    tmux select-pane -L
    tmux send-keys "$command" C-m
    tmux select-pane -R
  fi

  tmux attach-session -t $session
}

options=":r:"
command=

while getopts ${options} option; do
  case ${option} in
    r)
      command="$OPTARG"
      ;;
    h)
      usage
      ;;
    \?)
      # echo "Unknown option: ${OPTARG}." >&2; exit 1;;
      echo "Unknown option: ${OPTARG}."
      echo
      usage
      ;;
  esac
done

run "$command"
